### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by bkmar1192** [hcooper/snips-tts-polly#1]
Do you have instructions on how to install this on a raspberry pi?

**Comment by nanosonde** [comment]
Assuming Raspberry Pi and Raspbian.

Get AWS Credentials for AWS Polly from Amazon and place them in your home directory.
Here the user "pi" is used.

pi@snips:~ $ cat .aws/credentials
[default]
aws_secret_access_key = <your_access_key>
aws_access_key_id = <your_key_id>
pi@snips:~ $ cat .aws/config
[default]
region = eu-central-1
pi@snips:~ $

1) sudo pip3 install boto3
2) Edit AWS credentials (see above)
3) cp snips-tts-polly.py /usr/bin/snips-tts-polly
4) cp snips-tts-polly.service /etc/systemd/system/snips-tts-polly.service
5) sudo systemctl enable  snips-tts-polly.service
6) sudo systemctl start snips-tts-polly.service

**Comment by hcooper** [comment]
Thanks for replying @nanosonde.
